### ISSUE TITLE
$ python demo.py [--demo /path/to/image/or/folder] [--show_mask]

### ISSUE THREAD

**Issue by MingkunGao** [xingyizhou/ExtremeNet#12]
Hi,man!
I should try demo.py in terminal,but code find bug!
`loading parameters: cache/ExtremeNet_250000.pkl
building neural network...
module_file: models.ExtremeNet
total parameters: 198531504
loading parameters...
loading from cache/ExtremeNet_250000.pkl
Running  
Traceback (most recent call last):
  File "demo.py", line 150, in <module>
    height, width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'
`
Please tell me where bug ? THK!

**Comment by canghaiyunfan** [comment]
@MingkunGao  args.demo is None,you need to give the image path or folders of demo.
