### ISSUE TITLE
No module named 'networks.deeplab_resnet'

### ISSUE THREAD

**Issue by mathpopo** [xingyizhou/ExtremeNet#29]
hi  when  i run "demo.py",show "No module named 'networks.deeplab_resnet'" in dextr.py
i try to "pip install networks",but no effect.

**Comment by mathpopo** [comment]
i use cuda9.0,so i install these conda ub the base of cuda9.0

**Comment by xingyizhou** [comment]
Please make sure you have cloned Deep Extreme Cut.

**Comment by alaa-shubbak** [comment]
i cloned the deep extreme cut from this website : 
https://github.com/scaelles/DEXTR-PyTorch
but it doesn't work 
any help please
