### ISSUE TITLE
How to train extremenet with multi GPUs, such as 4*1080Ti.

### ISSUE THREAD

**Issue by Splendon** [xingyizhou/ExtremeNet#7]

**Comment by xingyizhou** [comment]
Hi, 
  You can change the batch size here https://github.com/xingyizhou/ExtremeNet/blob/master/config/ExtremeNet.json#L4 and images per batch here https://github.com/xingyizhou/ExtremeNet/blob/master/config/ExtremeNet.json#L22 (and make sure the sum of chunk_sizes equal to batch_size) to fit your GPUs.

**Comment by yezhengli-Mr9** [comment]
To retrain COCO, Is that possible that for weaker GPU hardwares, it is likely to have ```RuntimeError: CUDA error: out of memory```?

------
```CUDA_VISIBLE_DEVICES=1,2,3 python train.py ExtremeNet```
I ve changed  "batch_size": 12, "chunk_sizes": [4,4,4] for 3 GPUs:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/16505983/55124216-de59d580-50db-11e9-8970-df1194aafcf1.png">
