### ISSUE TITLE
How to train without the pre-trained cornernet model

### ISSUE THREAD

**Issue by bjnumber1** [xingyizhou/ExtremeNet#8]
thank u for your code very much，i don not want to  fine-tun from the cornernet model and how to train the model from scratch

**Comment by xingyizhou** [comment]
Hi, 
  Thanks for your interests. You can delete this line https://github.com/xingyizhou/ExtremeNet/blob/master/config/ExtremeNet.json#L26 to train from scratch. To fully reproduce our results, you will also need to increase the training iterations https://github.com/xingyizhou/ExtremeNet/blob/master/config/ExtremeNet.json#L18 . We have tried `"max_iter": 500000, "stepsize": 450000`, it works slightly better than fine-tuning CornerNet. Our model is given at https://drive.google.com/file/d/1omiOUjWCrFbTJREypuZaODu0bOlF_7Fg/view?usp=sharing .

**Comment by bjnumber1** [comment]
Thanks very much，it help me a lot.
